KingsComics/DjangoComicStore/urls.py
from users import forms 
from users import views as user_views

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webApp.urls',namespace = 'comicMain')),
    path('store/',include('store.urls',namespace= 'storeMain')),
    
    #Auth path
    path('register/',user_views.register,name = 'register'),
    path('login/',user_views.custom_login_view,name = 'login'),
    path('logout/',user_views.logout_view,name = 'logout'),
    
    #Password reset path
    path('password_reset/',auth_views.PasswordResetView.as_view(form_class = forms.forgotPasswordEmailVal, template_name = 'users/password_reset.html'),name= 'password-reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name = 'users/password_reset_done.html'),name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name = 'users/password_reset_confirm.html'),name = "password_reset_confirm"),
    path('password_reset_complete',auth_views.PasswordResetCompleteView.as_view(template_name = 'users/password_reset_complete.html'),name = 'password_reset_complete'),
    
    #Payment path
    path('checkout/',include('payments.urls',namespace = 'paymentsMain')),
    
    #Bookshelf path
    path('bookshelf/',user_views.Bookshelf.as_view(),name = 'bookshelf'),
    path('bookshelf/reader/<int:pk>/',user_views.comic_reader.as_view(),name ='bookshelf_reader'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

KingsComics/store/urls.py
from django.contrib import admin
from django.urls import path
from .views import StoreListView,ProductDetailView,AddToCart,ViewCart,RemoveItem

app_name = 'storeApp'

urlpatterns = [
    path('',StoreListView.as_view(),name = 'store-home'),
    path('comic/<int:pk>/',ProductDetailView.as_view(),name = 'store-detail'),
    path('comic/add_cart/<int:pk>/',AddToCart.as_view(),name = 'add-cart'),
    path('view_cart/',ViewCart.as_view(),name = 'view-cart'),
    path('remove_item/<int:pk>/',RemoveItem.as_view(),name = 'remove-item'),
    
]

KingsComics/webApp/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomePageView,contact


app_name = 'webApp'


urlpatterns = [
    path('',HomePageView.as_view(),name='comic-home'),
    path('contact/',contact,name = "contact"),
]

KingsComics/webApp/models.py
from django.db import models

class Newsletter(models.Model):
    name = models.CharField(max_length=30, unique=False)
    email = models.EmailField(unique=True)

    def __str__(self) -> str:
        return f'Name: {self.name}, Email: {self.email}'

KingsComics/webApp/forms.py
from django import forms
from django.core.validators import EmailValidator
from django.core.mail import send_mail

from crispy_forms.helper import FormHelper

from .models import Newsletter


class ContactForm(forms.Form):
    name = forms.CharField(max_length=20,label='Name',required=True,widget=forms.TextInput(attrs={'readonly':'readonly','class':'form-input contact-input'}))
    email = forms.EmailField(validators=[EmailValidator],label='Email',required=True,max_length=50,widget=forms.EmailInput(attrs={'readonly':'readonly', 'class':'form-input contact-input'}))
    subject = forms.CharField(max_length=50,label='Subject',widget= forms.TextInput(attrs={'class':'form-input contact-input'}))
    content = forms.CharField(label='Message',widget=forms.Textarea(attrs={'class':'form-control form-input contact-input','autocomplete':'off','placeholder':'Put your message here','maxlength':'400'}),required=True)

    def send_mail(self):
        
        subject = self.cleaned_data['subject']
        content = self.cleaned_data['content']
        sender = self.cleaned_data['email']
        send_mail(
            subject,
            content,
            sender,
            ['example_email@gmail.com']    
        )
    
    
class NewsletterForm(forms.ModelForm):

    name = forms.CharField(max_length=20,required=True,widget=forms.TextInput(attrs={'class':'newsletter-input newsletter-name','placeholder':'ENTER NAME'}))
    email = forms.EmailField(validators=[EmailValidator],required=True,max_length=100,widget = forms.EmailInput(attrs={'class':'newsletter-input newsletter-email','placeholder':'ENTER EMAIL'}))    

    class Meta:
        model = Newsletter
        fields=['name','email']
        

    def __init__(self, *args,**kwargs): 
        super().__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    
    def user_exists(self) -> bool:
        return Newsletter.objects.filter(email=self.cleaned_data['email']).exists()
    
    def send_test_mail(self)-> None:
        name,email = self.cleaned_data['name'],self.cleaned_data['email']
        subject = "Registering for Kings Comics Newsletter!"
        message = f"Hi {name},\nThankyou for registering for Kings Comics Newsletter.\nThis is a test email."
        send_mail(
            subject=subject,
            message=message,
            from_email='example_email@gmail.com',
            recipient_list=[email]
        )

        
    

        

KingsComics/webApp/views.py
from typing import Any

from django.views.generic.base import TemplateView
from django.contrib import messages
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required


from store.models import comic

from .forms import ContactForm,NewsletterForm
from .webApp_helpers import get_featured_cache



    
class HomePageView(TemplateView):
    """
    The main home page view showing popular comics filtered by purchases and
    featured comics. The featured comics and recently bought comics are stored in the
    memory cache. 
    """
    model = comic
    template_name = "webApp/home.html"
    
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)

        featured_comics = get_featured_cache()['featured_comics'] 
        comic_popular_queryset = comic.get_popular_comics(4)

        form = NewsletterForm(initial={'name': self.request.user.username,'email':self.request.user.email}) if self.request.user.is_authenticated else NewsletterForm()

        context.update({
            'featured_comics':featured_comics,
            'popular_comics':comic_popular_queryset,
            'form':form
        })

        return context
    
    def post(self,request):
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            form.send_test_mail()

            messages.success(request,"Thankyou for signing up!")
            return redirect('comicMain:comic-home') 
        else:
            messages.warning(request,"You have already signed up for the newsletter!")
            return redirect('comicMain:comic-home')
         

@login_required(login_url='login') 
def contact(request):
    """
    View for contact form, presets the field of username and email based on user details
    """

    form = ContactForm()
    form.fields['name'].initial = request.user.username
    form.fields['email'].initial = request.user.email
    
    if request.method == "POST":
        form = ContactForm(request.POST)
        
        if form.is_valid():
            form.send_mail()
            messages.success(request,"Your request has been successfuly sent")
            return redirect('comicMain:contact')
        else:
            messages.warning(request,'There was an error submitting your message')
            return redirect('comicMain:contact')
    
    return render(request,'webApp/contact.html',{'form':form})
            


    

KingsComics/webApp/templates/webApp/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'webApp/css/main.css' %}" type="text/css" rel="stylesheet"> 
    <link href="{% static 'webApp/css/store.css' %}" type="text/css" rel="stylesheet"> 
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poetsen+One&display=swap" rel="stylesheet">

    {% block additional_styles %}
    {%endblock%}

</head>
    <body class = "vh-100 ">
        <!-- Navbar -->
        
        <nav class="navbar navbar-expand-lg navbar-dark" >
            <div class="container-fluid">
              <a class="navbar-brand" href="#"><img class = "logo"  src="{% static 'webApp/images/logo.jpg'%}"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{%url 'comicMain:comic-home'%}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="{%url 'storeMain:store-home'%}">Store</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link active" href="{%url 'comicMain:contact'%}">Contact Us</a>
                  </li>
                </ul>
                <ul class = "navbar-nav ms-auto  mb-2 mb-lg-0">
                  <!-- Login dropdown if authenticated -->
                    {% if user.is_authenticated%}
                        <li class="nav-but">
                            <div class = 'dropdown'>
                              <a class="btn dropdown-toggle "   role="button" data-bs-toggle="dropdown" aria-expanded="false"><svg class="profile-image" xmlns="http://www.w3.org/2000/svg" width="40" height="50" viewBox="0 0 24 24"><g fill="#ffffff" fill-rule="evenodd" clip-rule="evenodd"><path d="M16 9a4 4 0 1 1-8 0a4 4 0 0 1 8 0m-2 0a2 2 0 1 1-4 0a2 2 0 0 1 4 0"></path><path d="M12 1C5.925 1 1 5.925 1 12s4.925 11 11 11s11-4.925 11-11S18.075 1 12 1M3 12c0 2.09.713 4.014 1.908 5.542A8.986 8.986 0 0 1 12.065 14a8.984 8.984 0 0 1 7.092 3.458A9 9 0 1 0 3 12m9 9a8.963 8.963 0 0 1-5.672-2.012A6.992 6.992 0 0 1 12.065 16a6.991 6.991 0 0 1 5.689 2.92A8.964 8.964 0 0 1 12 21"></path></g></svg></a>

                              <ul class="dropdown-menu">
                                <li><a class="dropdown-item " href="{%url 'bookshelf'%}">Bookshelf</a></li>
                                <li><a class="dropdown-item" href="{%url 'logout'%}">Logout</a></li>
                              </ul>
                            
                            </div>
                        </li>
                    {%else%}
                        <li class = "nav-but">
                          <a class="btn"  href="{%url 'login'%}"  ><svg class="profile-image" xmlns="http://www.w3.org/2000/svg" width="40" height="50" viewBox="0 0 24 24"><g fill="#ffffff" fill-rule="evenodd" clip-rule="evenodd"><path d="M16 9a4 4 0 1 1-8 0a4 4 0 0 1 8 0m-2 0a2 2 0 1 1-4 0a2 2 0 0 1 4 0"></path><path d="M12 1C5.925 1 1 5.925 1 12s4.925 11 11 11s11-4.925 11-11S18.075 1 12 1M3 12c0 2.09.713 4.014 1.908 5.542A8.986 8.986 0 0 1 12.065 14a8.984 8.984 0 0 1 7.092 3.458A9 9 0 1 0 3 12m9 9a8.963 8.963 0 0 1-5.672-2.012A6.992 6.992 0 0 1 12.065 16a6.991 6.991 0 0 1 5.689 2.92A8.964 8.964 0 0 1 12 21"></path></g></svg></a>
                        </li>
                    
                    {% endif %}


                    <!-- cart button -->
                    <form method="post">
                      {% csrf_token %}
                      <li class="nav-but">
                          <a class="btn" href="{%url 'storeMain:view-cart'%}"><img class = "cart-image" src="{%static 'webApp/images/cart.png' %}"></a>
                      </li>
                    </form>
                </ul>
              </div>
            </div>
          </div>
          </nav>

        <!-- Content -->
        {% if messages %}
        <div class="messages-div">
          <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}

        <main role = "main" class = "container-fluid main-bg" >

          {%block content%}
          {% endblock%}

            

        </main>

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script> 



    </body>
</html>

KingsComics/webApp/templates/webApp/contact.html
{%extends "webApp/base.html" %}
{% load crispy_forms_tags %}

{%block content%}

<div class = 'row  contact-row'>
    <div class = 'col-8 ' style="margin-left: 375px;">

        <div class = 'content-section pt-5'>
            <legend class = 'border-bottom mb-4 auth-header'>CONTACT US</legend>
            <form method = "POST">
                {% csrf_token %}

                <fieldset class = 'form-group' style="padding-left: 100px;">
                    {{form|crispy}}

                <button class = 'border-2 auth-submit'  type="submit">
                    <span class="auth-submit-text">Submit</span>
                </button>
            </form>


        </div>
    </div>
</div>
{%endblock content%}

KingsComics/webApp/templates/webApp/home.html
{% extends "webApp/base.html" %}
{% load static%}
{% load crispy_forms_tags %}

{%block additional_styles %}
<style>
  .navbar{
    background: transparent;
  }

</style>
{%endblock%}
{%block content%}
<div class="row home-bg" >
    <div class="sub-home-bg">
        <h1  class = 'sub-home-header'>
          AUSTRALIA'S VINTAGE COMIC & GRAPHIC NOVEL HQ
        </h1>
        <hr  class = 'sub-home-line'>
        <p class = 'sub-home-text'>
          King's comics prides itself on maintaing soft copies of and bringing light to vintage comics that should be preserved. With a true passion for delivering 
          a positive consumer experience we invite you to start reading with us!
        </p>

        <button class="arrow-btn">
          <svg height="1.2em" class="arrow" viewBox="0 0 512 512"><path d="M233.4 105.4c12.5-12.5 32.8-12.5 45.3 0l192 192c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L256 173.3 86.6 342.6c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3l192-192z"></path></svg>
        </button>

    </div>
</div>

<!-- Testing white background -->
<div class="row featured-row">
  <div class = 'featured-text'>
    <h1 class = 'featured-header'> MAY. 22ND</h1>
    <hr class= 'featured-line'>
    <h3 class = 'featured-subheader'> <span>NEW<span> RELEASES</h3>
    <a href="{%url 'storeMain:store-home'%}"><button class="featured-button">VIEW ALL COMICS</button></a>
  </div>


  <img class = 'featured-char-img' src="{% static 'webApp/images/home_char.png' %}">
  <img class = 'featured-char-img2' src="{% static 'webApp/images/home_char2.png'%}">
  <img class = 'featured-char-img3' src="{% static 'webApp/images/home_char3.png'%}">
  <a  class='featured-comic comic-lrg' id="comic-lrg1" href="{%url 'storeMain:store-detail' featured_comics.5.id %}"><img  class = "featured-img" src="{{featured_comics.5.cover.url}}"></a>
  <a  class='featured-comic comic-med' id="comic-med1" href="{%url 'storeMain:store-detail' featured_comics.0.id %}"><img  class = "featured-img" src="{{featured_comics.0.cover.url}}"></a>
  <a  class='featured-comic comic-med' id="comic-med2" href="{%url 'storeMain:store-detail' featured_comics.2.id %}"><img  class = "featured-img" src="{{featured_comics.2.cover.url}}"></a>
  <a  class='featured-comic comic-sml' id="comic-sml1" href="{%url 'storeMain:store-detail' featured_comics.4.id %}"><img  class = "featured-img" src="{{featured_comics.4.cover.url}}"></a>
</div>

<div class = 'row popular-bg'>
    <h3 class="popularchoices-text-header">OUR MOST </h3>
    <h1 class="popularchoices-text">POPULAR CHOICES</h1>
    <hr class="popularchoices-line">
    <div class = 'popularchoices-image-container col-10 '>
      {%for comic in popular_comics%}
      <a href="{%url 'storeMain:store-detail' comic.id%}" style="text-decoration: none; margin-right: 50px; margin-left: 80px;">
        <div class = "card popular-comic" style="background-color: transparent; color: white;">
            <img src="{{comic.cover.url}}" class = 'card-img' >

            <div class = 'card-body'>
                <h5 class = 'card-title'>{{comic.title}}</h5>
            </div>
        </div>
      </a>
      {%endfor%}
    </div>
</div>

<div id='newsletter-section'class = 'row newsletter-form'>
  <div class = 'col-8'>
    <h3>DON'T MISS NEW RELEASES!</h3>
    <h1>NEWSLETTER SIGNUP</h1>
    <hr>
    <form method="post">
      {%csrf_token%}
      
      <div class = 'newsletter-form-inputs'>
        {{form.name|as_crispy_field}}
        {{form.email|as_crispy_field}}
      </div>

      <button>
        <span>SIGN ME UP!</span>
      </button>  
    </form>
  </div>
</div>


<div class = 'row footer-row'>
  <img class = 'footer-logo' src="{%static 'webApp/images/logo.jpg'%}">
  <footer class="main-footer">
      <ul>
        {% if request.path != '/' %}
          <li class="footer-item"><a href="{%url 'comicMain:comic-home'%}" class="footer-item-link">HOME</a></li>
        {%else%}
          <li class="footer-item"><a href="#" class="footer-item-link">HOME</a></li>
        {%endif%}
          <li class="footer-item"><a href="{%url 'comicMain:contact'%}" class="footer-item-link">CONTACT</a></li>
          <li class="footer-item"><a href="{%url 'storeMain:store-home'%}" class="footer-item-link">STORE</a></li>
      </ul>  
  </footer>
</div>






{%endblock content%}