KingsComics/DjangoComicStore/urls.py
from users import forms 
from users import views as user_views

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webApp.urls',namespace = 'comicMain')),
    path('store/',include('store.urls',namespace= 'storeMain')),
    
    #Auth path
    path('register/',user_views.register,name = 'register'),
    path('login/',user_views.custom_login_view,name = 'login'),
    path('logout/',user_views.logout_view,name = 'logout'),
    
    #Password reset path
    path('password_reset/',auth_views.PasswordResetView.as_view(form_class = forms.forgotPasswordEmailVal, template_name = 'users/password_reset.html'),name= 'password-reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name = 'users/password_reset_done.html'),name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name = 'users/password_reset_confirm.html'),name = "password_reset_confirm"),
    path('password_reset_complete',auth_views.PasswordResetCompleteView.as_view(template_name = 'users/password_reset_complete.html'),name = 'password_reset_complete'),
    
    #Payment path
    path('checkout/',include('payments.urls',namespace = 'paymentsMain')),
    
    #Bookshelf path
    path('bookshelf/',user_views.Bookshelf.as_view(),name = 'bookshelf'),
    path('bookshelf/reader/<int:pk>/',user_views.comic_reader.as_view(),name ='bookshelf_reader'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

KingsComics/payments/urls.py
from django.contrib import admin
from django.urls import path
from .views import create_checkout_session,payment_cancelled,payment_success,payment_successful_webhook



app_name = 'paymentsApp'


urlpatterns = [
    path('',create_checkout_session,name = 'create-checkout'),
    path('payment_success/',payment_success,name = 'payment-success'),
    path('payment_cancelled/',payment_cancelled,name = 'payment-cancellled'),
    path('payment_success_webhook/',payment_successful_webhook,name='payment-success-webhook')
]

KingsComics/store/urls.py
from django.contrib import admin
from django.urls import path
from .views import StoreListView,ProductDetailView,AddToCart,ViewCart,RemoveItem

app_name = 'storeApp'

urlpatterns = [
    path('',StoreListView.as_view(),name = 'store-home'),
    path('comic/<int:pk>/',ProductDetailView.as_view(),name = 'store-detail'),
    path('comic/add_cart/<int:pk>/',AddToCart.as_view(),name = 'add-cart'),
    path('view_cart/',ViewCart.as_view(),name = 'view-cart'),
    path('remove_item/<int:pk>/',RemoveItem.as_view(),name = 'remove-item'),
    
]

KingsComics/webApp/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomePageView,contact


app_name = 'webApp'


urlpatterns = [
    path('',HomePageView.as_view(),name='comic-home'),
    path('contact/',contact,name = "contact"),
]

KingsComics/store/models.py
from django.db import models
from datetime import datetime as dt 

from typing import Any

class comic(models.Model):
    title = models.CharField(max_length = 50,unique =True)
    cover = models.ImageField(default='default.jpg')
    description = models.TextField(max_length = 300, blank = True)
    featured = models.BooleanField(default = False)
    company = models.CharField(max_length=50)
    purchases = models.PositiveIntegerField(default = 0)
    price = models.FloatField()
    release_date = models.DateTimeField()
    bundle = models.SmallIntegerField(blank = True, null = True)
    stripe_id = models.CharField(max_length = 300,blank = True,null = True)
    stripe_price_id = models.CharField(max_length = 300,blank = True, null = True)
    
    def __str__(self):
        return f'{self.title} comic. ${self.price} '
   
    def save(self,*args,**kwargs) -> None:
        
        self.price = round(float(self.price),2)

        #Save date as datetime object in format : Year-month-day 
        # release_date_obj = dt.strptime(self.release_date,r"%d-%m-%Y")
        # self.release_date = dt.strftime(release_date_obj,r"%Y-%m-%d")
        return super().save(*args,**kwargs)
    
    def generate_comic_data(self)->dict[str,Any]:
        comic_data = {'id':self.pk,'title':self.title,'price':self.price}
        return comic_data

    @classmethod
    def get_popular_comics(cls,lim:int):
        return cls.objects.filter(featured = False).order_by('-purchases')[:lim]
        
    

    

KingsComics/store/views.py
from typing import Any

from .models import comic

from users.models import Cart,UserProfile
from users.user_helpers import session_cart_to_db


from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.shortcuts import get_object_or_404
from django.contrib import messages

class StoreListView(ListView):
    """
    Main store page view, context data gets list of comics and uses for loop in template to show comics
    """
    model = comic
    
    template_name = "store/store_home.html"
    
    context_object_name = "comicList"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        
        context = super().get_context_data(**kwargs)
        search_request = self.request.GET.get('search')
        if search_request in [' ',"",None,"Search by title"]: 
            context['comics'] =comic.objects.all()
        else:
            context['comics'] = comic.objects.filter(title__icontains=search_request)
        
        return context




class ProductDetailView(DetailView):
    model = comic

    def get_context_data(self, **kwargs: Any): 
        context = super().get_context_data(**kwargs)

        #Detailed comic can be accessed from home or store page
        if 'HTTP_REFERER' in self.request.META.keys() and 'store' not in self.request.META['HTTP_REFERER']:
            context['back_url'] = reverse('comicMain:comic-home')
        else:
            context['back_url'] = reverse('storeMain:store-home')

        return context

    

class AddToCart(LoginRequiredMixin,View):
    
    #Get function to prevent url access to page
    def get(self,*args,**kwargs):
        return redirect('storeMain:store-home')
    
    def post(self,request,*args,**kwargs):
        """
        Adds comics to session cart upon post request 
        """ 
       
        comic_data= get_object_or_404(comic,pk = kwargs['pk']).generate_comic_data()
        user_bookshelf = get_object_or_404(UserProfile,user = request.user).bookshelf['comic']
        user_cart = get_object_or_404(Cart,user = request.user)
        session_cart:list = request.session['cart']
        
        if (comic_data in session_cart) or user_cart.is_comic_in_cart(comic_data['id']):
            messages.warning(request,"This item is already in your cart")
        elif comic_data['title'] in user_bookshelf:
            messages.warning(request,'This item is already in your bookshelf')
        else:
            session_cart.append(comic_data)
            request.session.save()
         
        return redirect('storeMain:store-detail',comic_data['id'])
        
class ViewCart(LoginRequiredMixin,ListView):
    """
    Add all products from session cart into db cart 
    """

    model =Cart
    
    def get(self, request, *args, **kwargs):
        
        try:
            session_cart = request.session['cart']
        except KeyError as e:
            print(f'Session cart not found: {e}')
            request.session['cart'] = []
            request.session.save()
            
        user_cart = get_object_or_404(Cart,user = request.user)   

        session_cart_to_db(session_cart,user_cart)

        request.session['cart'] = []
        request.session.save()
        
        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        user_cart = get_object_or_404(Cart,user = self.request.user)
        context['cart'] = user_cart.products.all()
        return context
        
    template_name = 'store/cart.html'
    context_object_name = 'object'


class RemoveItem(LoginRequiredMixin,View):
    """
    View to remove items in the cart 
    """ 

    def post(self,request,*args,**kwargs):
        
        comic_id = kwargs['pk']
        user_cart = get_object_or_404(Cart,user = request.user)
        user_cart.remove_from_cart(comic_id)
        return redirect('storeMain:view-cart')


            

KingsComics/store/templates/store/cart.html
{%extends "webApp/base.html" %}
{% load crispy_forms_tags %}
{% load static%}
{%block content%}

<div class = "row header-row mb-5 mt-5 ">
    <div class = 'col-10 offset-3 header-col-cart d-flex'>
        <h1 class = 'cart-header'>MY CART</h1>
    </div>
</div>
    
{%for product in cart %}
    
    <div class = 'row cart-item-row'>
        <div class = 'col-9 offset-3 d-flex'>
            <a class = 'cart-item' href="{%url 'storeMain:store-detail' product.id%}">
                <img class = 'cart-item-img' src="{{product.cover.url}}">
                <h5 class = 'cart-item-title'>{{product.title}}</h5>
                <h5 class ='cart-item-price'>${{product.price}}</h5>

                <form class = 'remove-item-form' method="post" action="{%url 'storeMain:remove-item' product.id%}">
                    {%csrf_token%}
                    <button class = 'remove-item'><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 256 256"><path fill="#ffffff" d="M202.83 197.17a4 4 0 0 1-5.66 5.66L128 133.66l-69.17 69.17a4 4 0 0 1-5.66-5.66L122.34 128L53.17 58.83a4 4 0 0 1 5.66-5.66L128 122.34l69.17-69.17a4 4 0 1 1 5.66 5.66L133.66 128Z" style="fill: rgb(0, 0, 0);"></path></svg></button>
                </form>
            </a> 
        </div>
    </div>
{%endfor%}

{%if cart%}
<div class = 'row' style="margin-top: 50px;">
    <div class = 'col offset-8'>
        <form class = 'payment-form' method = 'post' action = "{%url 'paymentsMain:create-checkout'%}">
            {%csrf_token%}
            <button class = 'btn-checkout btn btn-secondary'>Proceed to checkout</button>
        </form>
    </div>
</div>
{%endif%}
<div class = 'row spacing' style="margin-bottom: 400px;"></div>

<div class = 'row footer-row'>
  <img class = 'footer-logo' src="{%static 'webApp/images/logo.jpg'%}">
  <footer class="main-footer">
      <ul>
        {% if request.path != '/' %}
          <li class="footer-item"><a href="{%url 'comicMain:comic-home'%}" class="footer-item-link">HOME</a></li>
        {%else%}
          <li class="footer-item"><a href="#" class="footer-item-link">HOME</a></li>
        {%endif%}
          <li class="footer-item"><a href="{%url 'comicMain:contact'%}" class="footer-item-link">CONTACT</a></li>
          <li class="footer-item"><a href="{%url 'storeMain:store-home'%}" class="footer-item-link">STORE</a></li>
      </ul>  
  </footer>
</div>
{%endblock%}

KingsComics/store/templates/store/comic_detail.html
{%extends "webApp/base.html" %}
{% load crispy_forms_tags %}
{% load static%}
{%block content%}


<div class = 'row detailed-row'>
    <a href="{{back_url}}">
        <btn class="back-button">
            <img class="back-image" src="{%static 'webApp/images/icons8-arrow-50.png' %}" width="40px" >
        </btn>
    </a>
    <div class = 'img-col col-3 offset-3 '>
                
            <img class = 'detail-img' src="{{object.cover.url}}">

    </div>
    <div class = 'col-4 '>
        <h1 class="detail-title">{{object.title}}</h1>
        <small class = "text-muted"> Released on {{object.release_date|date:"M d, Y"}} by {{object.company}}</small>
        <h5 class = 'detail-price'>${{object.price}}</h5>

        <form method="post" action = '{% url "storeMain:add-cart" object.id %}'>
            {% csrf_token %}
            <button class="detail-cart-btn btn btn-secondary" >Add to cart <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 256 256"><path fill="#ffffff" d="m220.24 132.24l-72 72a6 6 0 0 1-8.48-8.48L201.51 134H40a6 6 0 0 1 0-12h161.51l-61.75-61.76a6 6 0 0 1 8.48-8.48l72 72a6 6 0 0 1 0 8.48"></path></svg></button>
        </form>
        <dt class = 'detailed-description-header'>Description</dt>
        <dd class = 'detailed-description-content'>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." </dd>

        <dt class = 'detailed-returns-header'>Returns</dt>
        <dd class = 'detailed-returns-content'>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</dd>
    </div>
</div>
{%endblock content%}
    

KingsComics/store/templates/store/store_home.html
{%extends "webApp/base.html" %}
{% load crispy_forms_tags %}
{% load static%}
{%block content%}

<div class = "row header-row " style="margin-top: 100px;">
    <h1>ALL PRODUCTS</h1>
</div>

<div class = 'row search-row'>
    <div class = 'col-4 search-col d-flex justify-content-end' style="margin-left: 50%;">
        <div class="input-form" >
            <form>
                <input class="search-input" type = 'text' name = 'search' placeholder="Search by title" value = "{{request.GET.title}}">
               
                <button class = 'search-button' type="submit"><img src="{%static 'webApp/images/search1.png'%}" height="30px"></button>
            </form>
        </div>
    </div>
</div>


<div class = "row firstRow" >
    <div class = "col-1"></div>
    <div class = 'col-10  productCol'>
        
        {%for comic in comics%}
            <!-- Single product card -->
            <a class = 'card-link' href="{%url 'storeMain:store-detail' comic.id%}">
                <div class = "card">
                        
                        <img src="{{comic.cover.url}}" class = 'card-img' >

                        <div class = 'card-body'>
                            <h5 class = 'card-title'>{{comic.title}}</h5>
                        
                            <span class = 'product-price'>${{comic.price}}</span>
                            
                            <div class = 'button-container'>
                                <button type = 'button' class="btn btn-sm card-add-btn">Add to cart</button>
                            </div>
                        </div>
                </div>
            </a>
        {%endfor%}





        
    </div>
    <div class = "col-1"></div>
</div>



<div class = 'row footer-row'>
  <img class = 'footer-logo' src="{%static 'webApp/images/logo.jpg'%}">
  <footer class="main-footer">
      <ul>
        {% if request.path != '/' %}
          <li class="footer-item"><a href="{%url 'comicMain:comic-home'%}" class="footer-item-link">HOME</a></li>
        {%else%}
          <li class="footer-item"><a href="#" class="footer-item-link">HOME</a></li>
        {%endif%}
          <li class="footer-item"><a href="{%url 'comicMain:contact'%}" class="footer-item-link">CONTACT</a></li>
          <li class="footer-item"><a href="{%url 'storeMain:store-home'%}" class="footer-item-link">STORE</a></li>
      </ul>  
  </footer>
</div>
{%endblock content%}